import argparse

def get_args():
    parser = argparse.ArgumentParser()

    parser.add_argument('--local-rank', default=0)
    parser.add_argument('--model_name', default="qwenvl25_7b")
    parser.add_argument('--model_path', type=str, default=None)
    parser.add_argument('--output_path', default="./eval")
    parser.add_argument('--chunk_size', type=int, default=64)
    parser.add_argument('--task', default="mlvu")
    parser.add_argument('--data_path', default="./data")
    parser.add_argument('--uniform_frame', type=int, default=450)
    parser.add_argument('--n_retrieval', type=int, default=20)
    parser.add_argument('--n_refine', type=int, default=5)
    parser.add_argument('--fps', type=float, default=1.0)
    parser.add_argument('--graph_path', type=str, default='./graphs')
    parser.add_argument('--total_pixels', type=int, default=16384)
    parser.add_argument('--duration', default="long,medium,short", type=str)
    parser.add_argument('--max_samples', type=int, default=None)
    parser.add_argument('--max_videos', type=int, default=None)
    parser.add_argument('--embedding_path', type=str, default="BAAI/bge-large-en-v1.5")
    parser.add_argument('--mlvu_subset', type=str, default=None)
    parser.add_argument('--mlvu_task_type', type=str, default=None)
    parser.add_argument('--mlvu_task', type=str, default=None)
    parser.add_argument('--debug_video_names', type=str, default=None)
    parser.add_argument('--semantic_merge_threshold', type=float, default=0.0)
    parser.add_argument('--adjacent_sim_threshold', type=float, default=0.95)
    parser.add_argument('--subtitle_merge_threshold', type=float, default=0.0)
    parser.add_argument('--max_supernode_span', type=int, default=4)
    parser.add_argument('--supernode_target_frames', type=int, default=None)
    parser.add_argument('--top_seed_k', type=int, default=12)
    parser.add_argument('--original_expand_hop', type=int, default=1)
    parser.add_argument('--original_rerank_topk', type=int, default=None)
    parser.add_argument('--supernode_expand_hop', type=int, default=0)
    parser.add_argument('--subtitle_novelty_threshold', type=float, default=1.0)
    parser.add_argument('--graph_only', action='store_true')
    parser.add_argument('--graph_min_frames', type=int, default=None)
    parser.add_argument('--direct_baseline', action='store_true')
    parser.add_argument('--keep_rank_checkpoints', action='store_true')
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument('--experiment_dir', type=str, default=None)

    # Training-free scene/event constraints applied on adjacent 64-frame chunks.
    parser.add_argument('--boundary_aware_merge', action='store_true')
    parser.add_argument('--scene_boundary_threshold', type=float, default=0.45)
    parser.add_argument('--event_boundary_threshold', type=float, default=0.45)
    parser.add_argument('--boundary_visual_weight', type=float, default=0.30)
    parser.add_argument('--boundary_motion_weight', type=float, default=0.25)
    parser.add_argument('--boundary_cross_motion_weight', type=float, default=0.20)
    parser.add_argument('--boundary_subtitle_weight', type=float, default=0.25)
    parser.add_argument('--boundary_frame_window', type=int, default=4)
    parser.add_argument('--boundary_spatial_size', type=int, default=64)
    parser.add_argument('--boundary_motion_scale', type=float, default=0.05)
    parser.add_argument('--boundary_cross_motion_scale', type=float, default=0.40)
    parser.add_argument('--boundary_debug', action='store_true')
    parser.add_argument('--boundary_diagnostics_dir', type=str, default=None)
    parser.add_argument('--boundary_visualization_dir', type=str, default=None)

    args = parser.parse_args()
    args.duration = args.duration.split(",")
    if args.debug_video_names:
        args.debug_video_names = [name.strip() for name in args.debug_video_names.split(",") if name.strip()]

    return args
